version: '3'

services:

  webapp:
    build: ./
    command: python bot.py
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    depends_on:
      - redis
    restart: on-failure

  redis:
    image: redis
    restart: on-failure
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - mongo_volume:/data/db
    restart: on-failure

volumes:
  mongo_volume:

networks:
  default:
    ipam:
      config:
        - subnet: "10.103.0.1/16"